# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/form_lite.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 619)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 400))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(True)
        Form.setTabletTracking(True)
        Form.setAcceptDrops(True)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.controls_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controls_frame.sizePolicy().hasHeightForWidth())
        self.controls_frame.setSizePolicy(sizePolicy)
        self.controls_frame.setMinimumSize(QtCore.QSize(0, 400))
        self.controls_frame.setObjectName("controls_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.controls_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.controls_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modelpathlineedit = QtWidgets.QLineEdit(self.groupBox_2)
        self.modelpathlineedit.setObjectName("modelpathlineedit")
        self.modelpathlineedit.setReadOnly(True)
        self.gridLayout_2.addWidget(self.modelpathlineedit, 0, 1, 1, 1)
        self.vizselectro = QtWidgets.QComboBox(self.groupBox_2)
        self.vizselectro.setObjectName("vizselectro")
        self.vizselectro.addItem("")
        self.vizselectro.addItem("")
        self.vizselectro.addItem("")
        self.gridLayout_2.addWidget(self.vizselectro, 2, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.deviceselector = QtWidgets.QComboBox(self.groupBox_2)
        self.deviceselector.setObjectName("deviceselector")
        self.gridLayout_2.addWidget(self.deviceselector, 1, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.modelchooserbtn = QtWidgets.QToolButton(self.groupBox_2)
        self.modelchooserbtn.setObjectName("modelchooserbtn")
        self.gridLayout_2.addWidget(self.modelchooserbtn, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.console = QtWidgets.QGroupBox(self.controls_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setObjectName("console")
        self.verticalLayout_3.addWidget(self.console)
        self.exporttrackbtn = QtWidgets.QPushButton(self.controls_frame)
        self.exporttrackbtn.setObjectName("exporttrackbtn")
        self.verticalLayout_3.addWidget(self.exporttrackbtn)
        self.exportreportbtn = QtWidgets.QPushButton(self.controls_frame)
        self.exportreportbtn.setObjectName("exportreportbtn")
        self.verticalLayout_3.addWidget(self.exportreportbtn)
        self.gridLayout_4.addWidget(self.controls_frame, 0, 1, 2, 1)
        self.info_groupBox_2 = QtWidgets.QGroupBox(Form)
        self.info_groupBox_2.setObjectName("info_groupBox_2")
        self.info_frame = QtWidgets.QGridLayout(self.info_groupBox_2)
        self.info_frame.setContentsMargins(9, 9, 9, 9)
        self.info_frame.setObjectName("info_frame")
        self.drawing_butt = QtWidgets.QFrame(self.info_groupBox_2)
        self.drawing_butt.setObjectName("drawing_butt")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.drawing_butt)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toggledrawingbtn = QtWidgets.QPushButton(self.drawing_butt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggledrawingbtn.sizePolicy().hasHeightForWidth())
        self.toggledrawingbtn.setSizePolicy(sizePolicy)
        self.toggledrawingbtn.setObjectName("toggledrawingbtn")
        self.horizontalLayout_2.addWidget(self.toggledrawingbtn)
        self.loadlinesbtn = QtWidgets.QPushButton(self.drawing_butt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadlinesbtn.sizePolicy().hasHeightForWidth())
        self.loadlinesbtn.setSizePolicy(sizePolicy)
        self.loadlinesbtn.setObjectName("loadlinesbtn")
        self.horizontalLayout_2.addWidget(self.loadlinesbtn)
        self.exportlinesbtn = QtWidgets.QPushButton(self.drawing_butt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportlinesbtn.sizePolicy().hasHeightForWidth())
        self.exportlinesbtn.setSizePolicy(sizePolicy)
        self.exportlinesbtn.setObjectName("exportlinesbtn")
        self.horizontalLayout_2.addWidget(self.exportlinesbtn)
        self.info_frame.addWidget(self.drawing_butt, 4, 0, 1, 1)
        self.infotable_1 = QtWidgets.QTableWidget(self.info_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infotable_1.sizePolicy().hasHeightForWidth())
        self.infotable_1.setSizePolicy(sizePolicy)
        self.infotable_1.setAutoFillBackground(False)
        self.infotable_1.setStyleSheet("QTableWidget {\n"
"            background-color: #ffffff;\n"
"            alternate-background-color: #f9f9f9;\n"
"            gridline-color: #e0e0e0;\n"
"            font-size: 14px;\n"
"            color: #333333;\n"
"        }\n"
"\n"
"        QHeaderView::section {\n"
"            background-color: #f0f0f0;\n"
"            color: #333333;\n"
"            padding: 4px;\n"
"            font-size: 14px;\n"
"            border: 1px solid #e0e0e0;\n"
"        }\n"
"\n"
"        QTableWidget::item {\n"
"            padding: 5px;\n"
"            border: none;\n"
"        }\n"
"\n"
"        QTableWidget::item:selected {\n"
"            background-color: #b0c4de;\n"
"            color: #333333;\n"
"        }\n"
"\n"
"        QTableWidget::item:hover {\n"
"            background-color: #f0f0f0;\n"
"        }\n"
"\n"
"        QTableCornerButton::section {\n"
"            background-color: #f0f0f0;\n"
"            border: 1px solid #e0e0e0;\n"
"        }")
        self.infotable_1.setObjectName("infotable_1")
        self.infotable_1.setColumnCount(2)
        self.infotable_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.infotable_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infotable_1.setHorizontalHeaderItem(1, item)
        self.info_frame.addWidget(self.infotable_1, 0, 0, 4, 1)
        self.infotable_2 = QtWidgets.QTableWidget(self.info_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infotable_2.sizePolicy().hasHeightForWidth())
        self.infotable_2.setSizePolicy(sizePolicy)
        self.infotable_2.setAutoFillBackground(False)
        self.infotable_2.setStyleSheet("QTableWidget {\n"
"            background-color: #ffffff;\n"
"            alternate-background-color: #f9f9f9;\n"
"            gridline-color: #e0e0e0;\n"
"            font-size: 14px;\n"
"            color: #333333;\n"
"        }\n"
"\n"
"        QHeaderView::section {\n"
"            background-color: #f0f0f0;\n"
"            color: #333333;\n"
"            padding: 4px;\n"
"            font-size: 14px;\n"
"            border: 1px solid #e0e0e0;\n"
"        }\n"
"\n"
"        QTableWidget::item {\n"
"            padding: 5px;\n"
"            border: none;\n"
"        }\n"
"\n"
"        QTableWidget::item:selected {\n"
"            background-color: #b0c4de;\n"
"            color: #333333;\n"
"        }\n"
"\n"
"        QTableWidget::item:hover {\n"
"            background-color: #f0f0f0;\n"
"        }\n"
"\n"
"        QTableCornerButton::section {\n"
"            background-color: #f0f0f0;\n"
"            border: 1px solid #e0e0e0;\n"
"        }")
        self.infotable_2.setObjectName("infotable_2")
        self.infotable_2.setColumnCount(6)
        self.infotable_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.infotable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infotable_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.infotable_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.infotable_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.infotable_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.infotable_2.setHorizontalHeaderItem(5, item)
        self.info_frame.addWidget(self.infotable_2, 0, 2, 5, 1)
        self.gridLayout_4.addWidget(self.info_groupBox_2, 1, 0, 1, 1)
        self.video_frame = QtWidgets.QFrame(Form)
        self.video_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_frame.setObjectName("video_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.video_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.video_panel = QtWidgets.QLabel(self.video_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_panel.sizePolicy().hasHeightForWidth())
        self.video_panel.setSizePolicy(sizePolicy)
        self.video_panel.setMinimumSize(QtCore.QSize(0, 400))
        self.video_panel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.video_panel.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_panel.setMouseTracking(True)
        self.video_panel.setTabletTracking(True)
        self.video_panel.setAcceptDrops(True)
        self.video_panel.setAutoFillBackground(True)
        self.video_panel.setFrameShape(QtWidgets.QFrame.Box)
        self.video_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_panel.setText("")
        self.video_panel.setAlignment(QtCore.Qt.AlignCenter)
        self.video_panel.setWordWrap(False)
        self.video_panel.setObjectName("video_panel")
        self.verticalLayout.addWidget(self.video_panel)
        self.frame_4 = QtWidgets.QFrame(self.video_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.videocurrenttime = QtWidgets.QLabel(self.frame_4)
        self.videocurrenttime.setObjectName("videocurrenttime")
        self.horizontalLayout.addWidget(self.videocurrenttime)
        self.playpausebtn = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playpausebtn.sizePolicy().hasHeightForWidth())
        self.playpausebtn.setSizePolicy(sizePolicy)
        self.playpausebtn.setObjectName("playpausebtn")
        self.horizontalLayout.addWidget(self.playpausebtn)
        self.loadvideobtn = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadvideobtn.sizePolicy().hasHeightForWidth())
        self.loadvideobtn.setSizePolicy(sizePolicy)
        self.loadvideobtn.setObjectName("loadvideobtn")
        self.horizontalLayout.addWidget(self.loadvideobtn)
        self.verticalLayout.addWidget(self.frame_4)
        self.gridLayout_4.addWidget(self.video_frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Model Settings"))
        self.vizselectro.setItemText(0, _translate("Form", "bbox"))
        self.vizselectro.setItemText(1, _translate("Form", "Track"))
        self.vizselectro.setItemText(2, _translate("Form", "bbox with track"))
        self.label_7.setText(_translate("Form", "Runtime Device :"))
        self.label_12.setText(_translate("Form", "Model path :"))
        self.label_8.setText(_translate("Form", "Visualization :"))
        self.modelchooserbtn.setText(_translate("Form", "..."))
        self.console.setTitle(_translate("Form", "Console"))
        self.exporttrackbtn.setText(_translate("Form", "Export Tracks"))
        self.exportreportbtn.setText(_translate("Form", "Export CSV Report"))
        self.info_groupBox_2.setTitle(_translate("Form", "Information Table"))
        self.toggledrawingbtn.setText(_translate("Form", "Start Drawing"))
        self.loadlinesbtn.setText(_translate("Form", "load lines"))
        self.exportlinesbtn.setText(_translate("Form", "export lines"))
        item = self.infotable_1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Line id"))
        item = self.infotable_1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Action"))
        item = self.infotable_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "File"))
        item = self.infotable_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Line id"))
        item = self.infotable_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Track Id"))
        item = self.infotable_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Crossing Time"))
        item = self.infotable_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Vehicle"))
        item = self.infotable_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Direction"))
        self.videocurrenttime.setText(_translate("Form", "00:00:00 SEC"))
        self.playpausebtn.setText(_translate("Form", "Play"))
        self.loadvideobtn.setText(_translate("Form", "Load Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
